# Generated by Django 5.1.6 on 2025-03-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentshield', '0003_skill_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('hr-manager', 'HR Manager')], default='candidate', max_length=20),
        ),
    ]
