# Generated by Django 5.1.6 on 2025-03-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talentshield', '0004_profile_role'),
    ]

    operations = [
    ]
