# Generated by Django 5.1.6 on 2025-03-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentshield', '0007_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('hr-manager', 'HR Manager')], default='candidate', max_length=20, verbose_name='Role'),
        ),
    ]
